"""
Django settings for clinic_system project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path
import dj_database_url
from dotenv import load_dotenv
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent


env_path = Path(BASE_DIR) / ".env"
load_dotenv(dotenv_path=env_path)


SECRET_KEY = os.environ.get("SECRET_KEY")
DEBUG = os.environ.get("DEBUG", "False") == "True"

ALLOWED_HOSTS = os.environ.get(
    "ALLOWED_HOSTS",
    "eyadatak.com,www.eyadatak.com,demo-clinic.onrender.com,127.0.0.1,localhost"
).split(",")

# Django 4.0+ requires every entry to include a scheme (http:// or https://).
# We also strip whitespace and drop empty strings, otherwise a stray comma or
# an empty env var would crash the system check (4_0.E001).
_csrf_raw = os.environ.get(
    "CSRF_TRUSTED_ORIGINS",
    "https://eyadatak.com,https://www.eyadatak.com,http://127.0.0.1,http://localhost"
)
CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in _csrf_raw.split(",")
    if o.strip() and "://" in o.strip()
]

# ─── Capacitor / mobile-app trusted origins ──────────────────────────────
# When the site runs inside the Capacitor native shell (iOS/Android), the
# webview origin is NOT the production domain — it's one of:
#   • iOS:     capacitor://localhost
#   • Android: https://localhost  (with a custom scheme allowlist)
#   • Both:    can be overridden via capacitor.config.ts -> server.hostname
# We extend CSRF_TRUSTED_ORIGINS so POSTs from the native shell don't 403,
# and SESSION_COOKIE_SAMESITE = 'None' so the session cookie is sent on
# cross-scheme requests (capacitor:// → https://api.eyadatak.com).
CSRF_TRUSTED_ORIGINS += [
    "capacitor://localhost",
    "ionic://localhost",
    "http://localhost",
    "https://localhost",
]
# In production, set SESSION_COOKIE_SAMESITE='None' AND SESSION_COOKIE_SECURE=True
# so the cookie is delivered over HTTPS from the native shell.
SESSION_COOKIE_SAMESITE = os.environ.get("SESSION_COOKIE_SAMESITE", "Lax")
CSRF_COOKIE_SAMESITE   = os.environ.get("CSRF_COOKIE_SAMESITE",   "Lax")

# ─── Security / SSL ─────────────────────────────────────────────────────
# All TLS-related toggles are controlled by a single `FORCE_SSL` env var
# instead of being derived from DEBUG. This is critical for two cases:
#   • Local dev with DEBUG=False (testing prod settings) — must be HTTP.
#   • A new DigitalOcean droplet that hasn't been issued a TLS cert yet
#     (e.g. before certbot runs) — also must be HTTP, otherwise nothing
#     responds. Once your cert + nginx are in place, set FORCE_SSL=True.
#
# When FORCE_SSL=True AND there's a reverse proxy (nginx/Caddy) terminating
# TLS in front of Django, also set USE_PROXY_SSL_HEADER=True so Django
# trusts the X-Forwarded-Proto header from the proxy.
FORCE_SSL = os.environ.get("FORCE_SSL", "False") == "True"

SESSION_COOKIE_SECURE = FORCE_SSL
CSRF_COOKIE_SECURE    = FORCE_SSL
SECURE_SSL_REDIRECT   = FORCE_SSL
SECURE_BROWSER_XSS_FILTER  = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"

# HSTS is browser-sticky: once a browser sees it, it'll force HTTPS for
# `SECURE_HSTS_SECONDS` even if you turn it off later. Keep it OFF until
# you're 100% certain TLS works on the public domain — including subdomains
# if SECURE_HSTS_INCLUDE_SUBDOMAINS is True.
SECURE_HSTS_SECONDS            = 31536000 if FORCE_SSL else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = FORCE_SSL
SECURE_HSTS_PRELOAD            = FORCE_SSL

# When Django sits behind nginx/Caddy doing TLS termination, the upstream
# request to gunicorn arrives over plain HTTP — but with a header marking
# the original scheme. Tell Django to trust that header so request.is_secure()
# and the redirect logic both behave correctly.
if os.environ.get("USE_PROXY_SSL_HEADER", "False") == "True":
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'patients',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'clinic_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'patients.context_processors.clinic_role_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'clinic_system.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(default='sqlite:///db.sqlite3')
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
STORAGES = {
    # Default storage — used by ImageField/FileField uploads (visit attachments).
    # Django 6.x requires this key to be present explicitly.
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Media (uploaded files — visit attachments)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / "media"

# Anthropic / Claude API key (used by AI medical assistance endpoint).
# Add ANTHROPIC_API_KEY=... to your local .env to enable AI suggestions.
ANTHROPIC_API_KEY = os.environ.get("ANTHROPIC_API_KEY", "")


# ─── Email (used for SignupRequest notifications) ────────────────────────
# Defaults to the console backend so dev never errors out — emails just
# print to stdout. To send real emails, set EMAIL_HOST, EMAIL_HOST_USER,
# EMAIL_HOST_PASSWORD in .env (and switch backend to SMTP).
EMAIL_BACKEND = os.environ.get(
    "EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend",
)
EMAIL_HOST          = os.environ.get("EMAIL_HOST", "")
EMAIL_PORT          = int(os.environ.get("EMAIL_PORT", "587"))
EMAIL_HOST_USER     = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS       = os.environ.get("EMAIL_USE_TLS", "True") == "True"
# Implicit SSL (port 465). Mutually exclusive with EMAIL_USE_TLS — Django
# raises ImproperlyConfigured if both are True. We force TLS off whenever
# SSL is on so a misconfigured pair doesn't crash the app.
EMAIL_USE_SSL       = os.environ.get("EMAIL_USE_SSL", "False") == "True"
if EMAIL_USE_SSL:
    EMAIL_USE_TLS = False
DEFAULT_FROM_EMAIL  = os.environ.get(
    "DEFAULT_FROM_EMAIL",
    "Eyadatak <info@eyadatak.com>",
)
# Where signup notifications get delivered. Comma-separated for multiple.
SIGNUP_NOTIFY_EMAILS = [
    e.strip() for e in os.environ.get(
        "SIGNUP_NOTIFY_EMAILS",
        "signup@eyadatak.com",
    ).split(",") if e.strip()
]
