# Generated by Django 6.0.3 on 2026-04-12 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_name', models.CharField(max_length=255)),
                ('clinic_specialty', models.CharField(default='عام', max_length=255)),
                ('doctor_name', models.CharField(max_length=255)),
                ('doctor_phone', models.CharField(max_length=20)),
                ('doctor_email', models.EmailField(max_length=254)),
                ('nurse_name', models.CharField(blank=True, max_length=255)),
                ('nurse_phone', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'جديد'), ('reviewed', 'تمت المراجعة'), ('approved', 'تم إنشاء الحساب'), ('rejected', 'مرفوض')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='clinic',
            name='clinic_number',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='رقم العيادة'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='plan',
            field=models.CharField(choices=[('basic', 'Basic'), ('pro', 'Pro')], default='basic', max_length=20),
        ),
        migrations.AddField(
            model_name='clinic',
            name='specialty',
            field=models.CharField(choices=[('general_practice', 'General Practice'), ('cardiology', 'Cardiology'), ('orthopedics', 'Orthopedics'), ('neurology', 'Neurology'), ('dermatology', 'Dermatology'), ('gynecology', 'Gynecology & Obstetrics'), ('dentistry', 'Dentistry')], default='general_practice', max_length=30),
        ),
        migrations.AddField(
            model_name='clinic',
            name='subscription_period',
            field=models.CharField(blank=True, choices=[('1_month', 'شهر واحد'), ('1_year', 'سنة واحدة')], max_length=20, null=True, verbose_name='مدة الاشتراك'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='subscription_start',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ بداية الاشتراك'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='trial_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='CT_MRI_findings',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='abdominal_circumference',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='visit',
            name='cardiac_history',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='cardiac_medications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='chest_pain_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='visit',
            name='contraception_method',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='visit',
            name='cycle_regularity',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='visit',
            name='ecg_results',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='ejection_fraction',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='visit',
            name='fetal_heart_rate',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='visit',
            name='fetal_movement',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='visit',
            name='fetal_position',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='visit',
            name='fundal_height',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='visit',
            name='gestational_age_weeks',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='injury_history',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='last_menstrual_period',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='neurological_examination',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='obstetric_history',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='pain_location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='visit',
            name='pain_scale',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='range_of_motion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='skin_examination',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='ultrasound_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='xray_findings',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'ذكر'), ('Female', 'أنثى')], max_length=10),
        ),
        migrations.CreateModel(
            name='VisitAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='visit_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='patients.visit')),
            ],
        ),
    ]
