# Generated by Django 6.0.3 on 2026-04-26 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_signuprequest_clinic_clinic_number_clinic_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='plan',
            field=models.CharField(default='basic', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='visit',
            name='follow_up_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ToothCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tooth_number', models.CharField(choices=[('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('31', '31'), ('32', '32'), ('33', '33'), ('34', '34'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45'), ('46', '46'), ('47', '47'), ('48', '48')], max_length=2)),
                ('surface', models.CharField(choices=[('whole', 'كامل'), ('O', 'إطباقي'), ('M', 'إنسي'), ('D', 'وحشي'), ('B', 'دهليزي'), ('L', 'لساني'), ('R', 'جذر')], default='whole', max_length=10)),
                ('condition', models.CharField(choices=[('healthy', 'سليم'), ('caries', 'تسوس'), ('filling', 'حشوة'), ('crown', 'تلبيس'), ('rct', 'سحب عصب'), ('fracture', 'كسر'), ('missing', 'مفقود'), ('to_extract', 'يحتاج خلع'), ('to_treat', 'يحتاج معالجة'), ('implant', 'زرعة'), ('bridge', 'جسر')], max_length=20)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tooth_conditions', to='patients.visit')),
            ],
            options={
                'indexes': [models.Index(fields=['visit'], name='patients_to_visit_i_a28d05_idx'), models.Index(fields=['tooth_number'], name='patients_to_tooth_n_cad5d3_idx')],
                'unique_together': {('visit', 'tooth_number', 'surface')},
            },
        ),
    ]
