# Generated by Django 6.0.3 on 2026-03-25 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='history',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='notes',
        ),
        migrations.AddField(
            model_name='visit',
            name='assigned_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_visits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visit',
            name='blood_pressure',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='visit',
            name='blood_sugar',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='visit',
            name='chief_complaint',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='clinic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='patients.clinic'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visit',
            name='clinical_examination',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_visits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visit',
            name='doctor_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='height',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='visit',
            name='history_of_present_illness',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='imaging_requests',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='lab_requests',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='nursing_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='patient_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='pulse',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('nurse_draft', 'مسودة تمريض'), ('doctor_completed', 'مكتملة من الطبيب')], default='nurse_draft', max_length=20),
        ),
        migrations.AddField(
            model_name='visit',
            name='temperature',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='visit',
            name='treatment_plan',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='visit_type',
            field=models.CharField(choices=[('first_visit', 'أول زيارة'), ('follow_up', 'مراجعة'), ('emergency', 'إسعاف'), ('consultation', 'استشارة')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visit',
            name='weight',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='visit',
            name='diagnosis',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='prescription',
            field=models.TextField(blank=True),
        ),
    ]
