# Generated by Django 6.0.3 on 2026-04-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_clinic_plan_alter_visit_follow_up_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toothcondition',
            name='surface',
            field=models.CharField(choices=[('whole', 'كامل'), ('O', 'إطباقي'), ('M', 'إنسي'), ('D', 'وحشي'), ('B', 'دهليزي'), ('L', 'لساني'), ('R', 'جذر'), ('MR', 'جذر إنسي'), ('DR', 'جذر وحشي'), ('PR', 'جذر حنكي')], default='whole', max_length=10),
        ),
    ]
