# Generated by Django 6.0.3 on 2026-05-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_alter_toothcondition_surface'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='ai_credits',
            field=models.PositiveIntegerField(default=0, verbose_name='رصيد التحليلات المشتراة'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='ai_daily_used',
            field=models.PositiveIntegerField(default=0, verbose_name='الاستخدام اليومي للذكاء الاصطناعي'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='ai_last_reset',
            field=models.DateField(blank=True, null=True, verbose_name='آخر تصفير لعدّاد اليوم'),
        ),
        migrations.AddField(
            model_name='visit',
            name='ai_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='ai_suggestions',
            field=models.TextField(blank=True, verbose_name='اقتراحات المساعد الذكي'),
        ),
        migrations.AlterField(
            model_name='toothcondition',
            name='surface',
            field=models.CharField(choices=[('whole', 'كامل'), ('O', 'إطباقي'), ('M', 'إنسي'), ('D', 'وحشي'), ('B', 'دهليزي/شفوي'), ('L', 'لساني/حنكي'), ('R', 'جذر'), ('MR', 'جذر إنسي'), ('DR', 'جذر وحشي'), ('PR', 'جذر حنكي')], default='whole', max_length=10),
        ),
    ]
