# Generated by Django 6.0.3 on 2026-05-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_clinic_ai_credits_clinic_ai_daily_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='specialty_type',
            field=models.CharField(blank=True, default='', help_text='النص الذي يظهر للطاقم في صفحة إدارة الحساب — مثال: "طب الأسرة" أو "أمراض القلب التداخلية".', max_length=120, verbose_name='التخصص (نص حر)'),
        ),
    ]
