# Generated by Django 6.0.3 on 2026-05-09 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_clinic_specialty_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('body', models.TextField(blank=True, default='', verbose_name='المحتوى')),
                ('url', models.CharField(blank=True, default='', help_text='رابط داخلي أو خارجي يفتح عند الضغط على الإشعار.', max_length=500, verbose_name='رابط (اختياري)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('read_by_clinics', models.ManyToManyField(blank=True, related_name='read_notifications', to='patients.clinic', verbose_name='قُرأ من قِبل')),
                ('target_clinic', models.ForeignKey(blank=True, help_text='اتركه فارغاً لإرسال الإشعار لجميع العيادات.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targeted_notifications', to='patients.clinic', verbose_name='العيادة المستهدفة')),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات',
                'ordering': ('-created_at',),
            },
        ),
    ]
