# Generated by Django 6.0.3 on 2026-05-13 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد'),
        ),
        migrations.AddField(
            model_name='visit',
            name='prescription_items',
            field=models.TextField(blank=True, default='', verbose_name='وصفة الأدوية (جدولية)'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('nurse_draft', 'مسودة تمريض'), ('doctor_completed', 'مكتملة من الطبيب'), ('consultation_pending', 'استشارة قيد الانتظار')], default='nurse_draft', max_length=20),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField(verbose_name='موعد الزيارة')),
                ('appt_type', models.CharField(choices=[('follow_up', 'مراجعة'), ('first_visit', 'زيارة أولى'), ('consultation', 'استشارة'), ('procedure', 'إجراء / معالجة'), ('other', 'أخرى')], default='follow_up', max_length=20, verbose_name='نوع الموعد')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('status', models.CharField(choices=[('scheduled', 'مجدول'), ('done', 'تم'), ('cancelled', 'ملغى')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.clinic')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_appointments', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient')),
            ],
            options={
                'ordering': ('scheduled_at',),
                'indexes': [models.Index(fields=['clinic', 'scheduled_at'], name='patients_ap_clinic__313826_idx'), models.Index(fields=['patient'], name='patients_ap_patient_8f86b9_idx')],
            },
        ),
    ]
