# Generated by Django 6.0.3 on 2026-05-15 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_patient_birth_date_visit_prescription_items_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('priority', models.CharField(choices=[('urgent', 'عاجل'), ('necessary', 'ضروري'), ('optional', 'اختياري')], default='necessary', max_length=20)),
                ('status', models.CharField(choices=[('planned', 'مخطط'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('cancelled', 'ملغى')], default='planned', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_plans', to='patients.patient')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PlanStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tooth_number', models.CharField(choices=[('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('31', '31'), ('32', '32'), ('33', '33'), ('34', '34'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45'), ('46', '46'), ('47', '47'), ('48', '48')], max_length=2)),
                ('surface', models.CharField(choices=[('whole', 'كامل'), ('O', 'إطباقي'), ('M', 'إنسي'), ('D', 'وحشي'), ('B', 'دهليزي/شفوي'), ('L', 'لساني/حنكي'), ('R', 'جذر'), ('MR', 'جذر إنسي'), ('DR', 'جذر وحشي'), ('PR', 'جذر حنكي')], default='whole', max_length=10)),
                ('procedure', models.CharField(choices=[('filling_composite', 'حشوة كومبوزيت'), ('filling_amalgam', 'حشوة أملغم'), ('rct', 'سحب عصب'), ('extraction', 'خلع'), ('crown', 'تلبيس'), ('crown_temp', 'تلبيس مؤقت'), ('bridge', 'جسر'), ('implant', 'زرعة'), ('cleaning', 'تنظيف وتلميع'), ('whitening', 'تبييض'), ('post_core', 'دعامة لبية'), ('other', 'أخرى')], max_length=30)),
                ('priority', models.CharField(choices=[('urgent', 'عاجل'), ('necessary', 'ضروري'), ('optional', 'اختياري')], default='necessary', max_length=20)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('notes', models.CharField(blank=True, default='', max_length=300)),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('done', 'تم')], default='pending', max_length=20)),
                ('canals', models.CharField(blank=True, default='', help_text='Comma-separated canal codes for RCT, e.g. "MB,DB,P".', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='patients.treatmentplan')),
            ],
            options={
                'ordering': ('sequence', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='VisitPlanSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='patients.planstep')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_snapshots', to='patients.visit')),
            ],
        ),
        migrations.CreateModel(
            name='VisitProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tooth_number', models.CharField(choices=[('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('31', '31'), ('32', '32'), ('33', '33'), ('34', '34'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45'), ('46', '46'), ('47', '47'), ('48', '48')], max_length=2)),
                ('surface', models.CharField(choices=[('whole', 'كامل'), ('O', 'إطباقي'), ('M', 'إنسي'), ('D', 'وحشي'), ('B', 'دهليزي/شفوي'), ('L', 'لساني/حنكي'), ('R', 'جذر'), ('MR', 'جذر إنسي'), ('DR', 'جذر وحشي'), ('PR', 'جذر حنكي')], default='whole', max_length=10)),
                ('surfaces_csv', models.CharField(blank=True, default='', help_text='Comma-separated extra surfaces for multi-surface procedures, e.g. "O,M".', max_length=60)),
                ('procedure', models.CharField(choices=[('filling_composite', 'حشوة كومبوزيت'), ('filling_amalgam', 'حشوة أملغم'), ('rct', 'سحب عصب'), ('extraction', 'خلع'), ('crown', 'تلبيس'), ('crown_temp', 'تلبيس مؤقت'), ('bridge', 'جسر'), ('implant', 'زرعة'), ('cleaning', 'تنظيف وتلميع'), ('whitening', 'تبييض'), ('post_core', 'دعامة لبية'), ('other', 'أخرى')], max_length=30)),
                ('material', models.CharField(blank=True, default='', max_length=80)),
                ('canals', models.CharField(blank=True, default='', max_length=120)),
                ('notes', models.CharField(blank=True, default='', max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plan_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedures', to='patients.planstep')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dental_procedures', to='patients.visit')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ToothStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tooth_number', models.CharField(choices=[('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('31', '31'), ('32', '32'), ('33', '33'), ('34', '34'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45'), ('46', '46'), ('47', '47'), ('48', '48')], max_length=2)),
                ('surface', models.CharField(choices=[('whole', 'كامل'), ('O', 'إطباقي'), ('M', 'إنسي'), ('D', 'وحشي'), ('B', 'دهليزي/شفوي'), ('L', 'لساني/حنكي'), ('R', 'جذر'), ('MR', 'جذر إنسي'), ('DR', 'جذر وحشي'), ('PR', 'جذر حنكي')], default='whole', max_length=10)),
                ('condition', models.CharField(choices=[('healthy', 'سليم'), ('caries', 'تسوس'), ('existing_filling', 'حشوة موجودة'), ('existing_crown', 'تلبيس موجود'), ('existing_rct', 'سحب عصب سابق'), ('fracture', 'كسر'), ('wear', 'تآكل'), ('missing', 'مفقود'), ('implant', 'زرعة'), ('discoloration', 'تصبغ')], max_length=20)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_updated_visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='patients.visit')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tooth_statuses', to='patients.patient')),
            ],
            options={
                'indexes': [models.Index(fields=['patient'], name='patients_to_patient_3eb37a_idx'), models.Index(fields=['patient', 'tooth_number'], name='patients_to_patient_0f7621_idx')],
                'unique_together': {('patient', 'tooth_number', 'surface')},
            },
        ),
        migrations.AddIndex(
            model_name='planstep',
            index=models.Index(fields=['plan'], name='patients_pl_plan_id_299c21_idx'),
        ),
        migrations.AddIndex(
            model_name='planstep',
            index=models.Index(fields=['tooth_number'], name='patients_pl_tooth_n_3f6396_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='visitplansnapshot',
            unique_together={('visit', 'plan_step')},
        ),
        migrations.AddIndex(
            model_name='visitprocedure',
            index=models.Index(fields=['visit'], name='patients_vi_visit_i_d1e616_idx'),
        ),
        migrations.AddIndex(
            model_name='visitprocedure',
            index=models.Index(fields=['tooth_number'], name='patients_vi_tooth_n_f84fba_idx'),
        ),
    ]
