# Generated by Django 6.0.3 on 2026-05-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_treatmentplan_planstep_visitplansnapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planstep',
            name='surfaces_csv',
            field=models.CharField(blank=True, default='', help_text='Comma-separated extra surfaces for a multi-surface step, e.g. "O,M".', max_length=60),
        ),
        migrations.AddField(
            model_name='toothstatus',
            name='surfaces_csv',
            field=models.CharField(blank=True, default='', help_text='Comma-separated extra surfaces for a multi-surface finding, e.g. "O,M".', max_length=60),
        ),
    ]
