# Generated by Django 6.0.3 on 2026-06-14 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_planstep_surfaces_csv_toothstatus_surfaces_csv'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='address',
            field=models.CharField(blank=True, default='', help_text='عنوان العيادة الذي يظهر في صفحة إدارة الحساب وعلى الوصفة الطبية.', max_length=255, verbose_name='عنوان العيادة'),
        ),
    ]
