# Generated by Django 6.0.3 on 2026-07-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_clinic_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='phone',
            field=models.CharField(blank=True, default='', help_text='رقم هاتف العيادة الذي يظهر بجانب العنوان على الوصفة الطبية.', max_length=30, verbose_name='هاتف العيادة'),
        ),
    ]
